# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-02-17 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cfirst_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clast_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='first_name',
            new_name='Cemail',
        ),
        migrations.RenameField(
            model_name='cemail',
            old_name='first_name',
            new_name='e_mail',
        ),
    ]
