# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-02-17 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20210217_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=128)),
                ('l_name', models.CharField(max_length=128)),
                ('e_mail', models.EmailField(max_length=128, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Cemail',
        ),
        migrations.DeleteModel(
            name='Cfirst_name',
        ),
        migrations.DeleteModel(
            name='Clast_name',
        ),
    ]
